Build nceplibs, use external libraries, and build different configurations in parallel (#15)
* creating a separate script for building libs used by shield build and making the exec folder specific to build config

* updates nceplibs to latest version, new build scripts for libfms and nceplibs, introduces the option to use externally stored nceplibs and libFMS.

* Adding license header, improving the external_libs option in COMPILE

* Correcting Error in last commit

* Removing prebuilt nceplibs.  Modifying COMPILE to build libFMS and nceplibs if they dont exist or if cleanall option is given. Modified BUILDlibFMS and BUILDnceplibs so that they can be run standalone.

* moving module load cmake to site specific environment file, adding cmake flag in BUILDnceplibs to avoid a compilation issue with systems using a standard less than C99, fixing one more reference to the location of libFMS

diff --git a/Build/COMPILE b/Build/COMPILE
--- a/Build/COMPILE
+++ b/Build/COMPILE
@@ -11,7 +11,7 @@
 #* (at your option) any later version.
 #*
 #* The SHiELD Build System distributed in the hope that it will be
-#* useful, but WITHOUT ANYWARRANTY; without even the implied warranty
+#* useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 #* of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 #* See the GNU General Public License for more details.
 #*
@@ -129,6 +129,7 @@ fi
 export BUILD_ROOT=${PWD%/*}
 export SHiELD_SRC=${PWD%/*/*}/SHiELD_SRC/
 export PATH="${BUILD_ROOT}/mkmf/bin:${BUILD_ROOT}/Build/mk_scripts:${PATH}"
+export NCEP_DIR=${BUILD_ROOT}/Build
 
 #
 # load the proper environment for your machine
@@ -151,65 +152,83 @@ sleep 5
 #
 # conditionally clean the build directory
   if [ ${clean} = "cleanall" ] ; then
-     echo " cleaning FMS library and build directory in 2 seconds"
+     echo " cleaning FMS library, nceplibs and build directory in 2 seconds"
      sleep 2
      \rm -rf libFMS/${compiler}/*
-     \rm -rf exec/${config}_${compiler}/*
+     \rm -rf exec/${config}_${hydro}.${comp}.${bit}.${compiler}/*
+     \rm -rf nceplibs/${compiler}/*
   elif [ ${clean} = "clean" ] ; then
      echo " cleaning build directory in 2 seconds"
      sleep 2
-     \rm -rf exec/${config}_${compiler}/*
+     \rm -rf exec/${config}_${hydro}.${comp}.${bit}.${compiler}/*
   fi
 
+# If EXTERNAL_LIBS is set, then the program will use the path defined by
+#    EXTERNAL_LIBS as the location of nceplibs and libFMS
+  if [ ! -z ${EXTERNAL_LIBS} ] ; then
+    echo " External Libraries are being used: ${EXTERNAL_LIBS}"
+    export NCEP_DIR=${EXTERNAL_LIBS}
+  fi
 #
 # check to make sure libFMS exists
-  if [ -d libFMS/${compiler} ] && [ -e libFMS/${compiler}/32bit/libFMS.a ] && [ -e libFMS/${compiler}/64bit/libFMS.a ] ; then
-     echo " pre-built libFMS/${compiler} exists"
+  if [ -d ${NCEP_DIR}/libFMS/${compiler} ] && [ -e ${NCEP_DIR}/libFMS/${compiler}/32bit/libFMS.a ] && \
+     [ -e ${NCEP_DIR}/libFMS/${compiler}/64bit/libFMS.a ] ; then
+     echo " pre-built ${NCEP_DIR}/libFMS/${compiler} exists"
   else
-     echo " libFMS/${compiler} does not exist - building libFMS/${compiler}"
-     MAKE_libFMS ${compiler}  >> build_libFMS_${compiler}.out 2>&1   # build 32bit and 64bit versions of libFMS
-     #
-     # test and report on libFMS build success
+     echo " ${NCEP_DIR}/libFMS/${compiler} does not exist"
+     ./BUILDlibfms ${compiler}
      if [ $? -ne 0 ] ; then
-       echo ">>> libFMS $compiler build failed"
-       exit 2
+        echo ">>> ${NCEP_DIR}/Libfms/${compiler} build failed"
+        exit 2
      fi
-     echo " libFMS build successful"
+  fi
+# check to make sure nceplibs exists
+  if [ -d ${NCEP_DIR}/nceplibs/${compiler} ] && [ -e ${NCEP_DIR}/nceplibs/${compiler}/libbacio.a ] && \
+     [ -e ${NCEP_DIR}/nceplibs/${compiler}/libsp_d.a ] && [ -e ${NCEP_DIR}/nceplibs/${compiler}/libw3emc_d.a ] && \
+     [ -e ${NCEP_DIR}/nceplibs/${compiler}/libw3nco_d.a ] ; then
+     echo " pre-built ${NCEP_DIR}/nceplibs/${compiler} exists"
+  else
+     echo " ${NCEP_DIR}/nceplibs/${compiler} does not exist"
+     ./BUILDnceplibs ${compiler}
+     if [ $? -ne 0 ] ; then
+        echo ">>> ${NCEP_DIR}/ncepdir/${compiler} build failed"
+        exit 3
+     fi
   fi
 
 #
 # ensure the build and final executable locations are available
-  mkdir -p ./exec/${config}_${compiler}
+  mkdir -p ./exec/${config}_${hydro}.${comp}.${bit}.${compiler}
   mkdir -p ./bin/
 
 # build the model
 echo -e "  building ${config} ${hydro} ${comp} ${bit} ${compiler} \t `date`"
   #
   # create the file list for the build
-    mk_paths ${config} ${compiler}                      > build_${config}_${hydro}.${comp}.${bit}.${compiler}.out 2>&1
+    mk_paths ${config} ${hydro} ${comp} ${bit} ${compiler}       > build_${config}_${hydro}.${comp}.${bit}.${compiler}.out 2>&1
     if [ $? -ne 0 ] ; then
        echo ">>> filelist cration failed"
-       exit 3
-    fi
-  #
-  # create the library makefiles
-    mk_makefile ${config} ${hydro} ${bit} ${compiler}  >> build_${config}_${hydro}.${comp}.${bit}.${compiler}.out 2>&1
-    if [ $? -ne 0 ] ; then
-       echo ">>> makefile creation failed"
        exit 4
     fi
   #
+  # create the library makefiles
+    mk_makefile ${config} ${hydro} ${comp} ${bit} ${compiler}    >> build_${config}_${hydro}.${comp}.${bit}.${compiler}.out 2>&1
+    if [ $? -ne 0 ] ; then
+       echo ">>> makefile creation failed"
+       exit 5
+    fi
+  #
   # build the configuration
-    mk_make ${config} ${comp} ${bit} ${avx} ${compiler}          >> build_${config}_${hydro}.${comp}.${bit}.${compiler}.out 2>&1
+    mk_make ${config} ${hydro} ${comp} ${bit} ${avx} ${compiler} >> build_${config}_${hydro}.${comp}.${bit}.${compiler}.out 2>&1
   #
   # move the executable to an accessible area
-    mv exec/${config}_${compiler}/test.x bin/${config_name}_${hydro}.${comp}.${bit}.${compiler}.x
+    mv exec/${config}_${hydro}.${comp}.${bit}.${compiler}/test.x bin/${config_name}_${hydro}.${comp}.${bit}.${compiler}.x
 
 #
 # test and report on build success
   if [ $? -ne 0 ] ; then
      echo ">>> ${config_name} build ${hydro} ${comp} ${bit} ${compiler} failed"
-     exit 5
+     exit 6
   else
      echo " ${config_name} build ${hydro} ${comp} ${bit} ${compiler} successful"
   fi
